[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
api = { path = "../api" }
clap = { version = "4.5.23", features = ["derive"] }
serde_json = "1.0.133"
simd-json = "0.14.3"
