[package]
name = "tf_idf"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
fetch = { path = "../fetch" }
simd-json = "0.14.3"
anyhow = "1.0.94"
serde = "1.0.216"
directories = "5.0.1"
