name: Lua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Download LuaJIT
      run: sudo apt-get install luajit
    - name: Download LuaRocks
      run: sudo apt-get install luarocks
    - name: Install LuaFileSystem
      run: sudo luarocks install luafilesystem
    - name: Test search index
      run: luajit ./tests/search_index.lua
