[package]
name = "rfsee-fetch"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Turner"]
repository = "https://github.com/matthewmturner/rfsee"

[dependencies]
anyhow = "1.0.94"
native-tls = "0.2.12"
